//////////////////////////////////////////////////////////////////
//		ZIN_getNamespace          //   
//////////////////////////////////////////////////////////////////
//
//	AUTHOR: 		goto kazufumi
//
//	CREATION DATE: 	2012_05_03
//	UPDATED DATE:		2012_05_03
//
//	VERSION:		1.0
//
//	HOW TO USE:		run "ZIN_getNamespace();"
//
//////////////////////////////////////////////////////////////////

/*============================================

	更新：
	
============================================*/

/*--------------------------------------------------------------------------------

	ZIN_getNamespace( string $obj )
	
	引数	オブジェクト名
	
	戻り値	string ネームスペース
	
	引数として受け取ったオブジェクト名からネームスペースだけを
	返します。
	
--------------------------------------------------------------------------------*/

global proc string ZIN_getNamespace( string $obj ){

	string $parts[];
	int $size = `tokenize $obj ":" $parts`;

	if( $size <= 1 ){
		return "";
	}else{
		string $namespace;
		for( $i=0; $i<($size-1); $i++ ){
			if( $i == 0 ){
				$namespace = $parts[0];
			}else{
				$namespace = $namespace + ":" + $parts[$i];
			}
		}
		return $namespace;
	}
}
