//////////////////////////////////////////////////////////////////
//	ZIN_rewritePath       //
//////////////////////////////////////////////////////////////////
//
//	AUTHOR: 		goto kazufumi
//
//	CREATION DATE:	2013_03_30
//	UPDATED DATE:	2013_03_30
//
//	VERSION:		1.0
//
//	HOW TO USE:		run "ZIN_rewritePath( ディレクトリパス )"
//
/////////////////////////////////////////////////////////////////////////////////////

/*---------------------------------------------------------------------------------------------------

	ZIN_rewritePath( ディレクトリパス )

	ディレクトリパスのスラッシュ（\）をバックスラッシュ（/）に変換して返します。
	
	戻り値：		スラッシュをバックスラッシュに変換したディレクトリパス

---------------------------------------------------------------------------------------------------*/

global proc string ZIN_rewritePath( string $path ){

	string $parts[];
	int $token = ` tokenize $path "\\" $parts `;
	string $return;
	for( $i=0; $i<$token; $i++ ){
		$return += $parts[$i];
		if( $i != $token-1 ){
			$return += "/";
		}else{
			int $size = ` size $path `;
			string $lastWord = ` substring $path $size $size `;
			if( $lastWord == "\\" ){
				$return += "/";
			}
		}
  }
	
	return $return;

}



