//////////////////////////////////
//	ZIN_existLocalMELConfig       //
//////////////////////////////////////////////////////////////////
//
//	AUTHOR: 		goto kazufumi
//
//	CREATION DATE:	2013_03_30
//	UPDATED DATE:	2013_03_30
//
//	VERSION:		1.0
//
//	HOW TO USE:		run "ZIN_existLocalMELConfig"
//
//////////////////////////////////////////////////////////////////

/*---------------------------------------------------------------------------------------------------

	ZIN_existLocalMELConfig

	仁ツールのローカル設定フォルダが存在するかを調査し、存在しない場合フォルダを作成する。
	戻り値：		存在しないとき　0
					存在するとき　　1

---------------------------------------------------------------------------------------------------*/

global proc int ZIN_existLocalMELConfig(){

	string $melConfig = "C:/ZIN/MEL/config";
	int $existMelConfig = `filetest -e $melConfig`;

	if($existMelConfig == 0){
		sysFile -makeDir $melConfig;
		return 0;
	}else if($existMelConfig == 1){
		return 1;
	}
}
