///////////////////////////////////////////////////////////////////////////////
//	PSTR_M_moveSkinJointsTool            //		
///////////////////////////////////////////////////////////////////////////////
//
//	AUTHOR: 		goto kazufumi
//
//	CREATION DATE:	2016_04_21
//	UPDATED DATE:	2016_04_21
//
//	VERSION:			1.0
//
//	HOW TO USE:		run "PSTR_M_moveSkinJointsTool();"
//
//////////////////////////////////////////////////////////////////

/*=======================================================

	PSTR_M_moveSkinJointsTool
	
=======================================================*/

/*-------------------------------------------------------------------------------------------------------

	çXêV

-------------------------------------------------------------------------------------------------------*/

global proc PSTR_M_moveSkinJointsTool(){

	string $sel[] = ` ls -sl `;

	string $code = `textField -q -text PST_tfCordName`;
	int $size = `size $code`;
	if( $size != 0 ){
		string $last = `substring $code $size $size`;
		if( $last != "_" ){
			if( $last != ":" ){
				$code += "_";
			}
		}
	}
	
	string $mesh_grp = $code + "mesh_grp";
	select -r $mesh_grp;
	
	MoveSkinJointsTool;
	
	select -r $sel;
	
	
}





